### ISSUE TITLE
Look into templating for CWL edit

### ISSUE THREAD

**Issue by tthyer** [Sage-Bionetworks-Workflows/cwl-tool-template#15]
Currently CWL edit step uses a python script; considering using templating such as moustache, handlebars, etc.

**Comment by BrunoGrandePhD** [comment]
Using a templating approach would help solve a few issues, including #13 (as Tess mentioned). There are a few ways we could tackle this. 

One approach that was mentioned during our Dockstore call is the use a "presentation repositories", which would contain the "rendered" versions of the CWL/Docker files, if I understood correctly. This would involve doubling the number of repositories under this organization, which seems cumbersome. 

Another approach is to have a "presentation branch" within the same repository, which would contain the "rendered" versions of the CWL/Docker files. This would be simpler than keeping track of multiple repositories. GitHub Actions already have push access to the repo in question with `GITHUB_TOKEN`, as opposed to the additional work required to ensure write-access to separate presentation repositories. The presentation branch could be the default that's visited on the GitHub website.

**Comment by tthyer** [comment]
@BrunoGrandePhD, I feel the idea of a presentation branch is definitely preferable to a completely separate repository, but I still favor the idea of using templating. With a presentation branch then you have only one branch that has finished, publishable output. With the current CICD design, though it's rough, you can always just change the target branch for the run and get output -- even if multiple developers are working at once. Doing the thought experiment of multiple developers working at once using presentation branches, that could be done too, if they're create additional presentation branches, but it seems more complicated.   It's probably appropriate at this point to draw up designs for the two alternatives and weigh pros and cons. The main con I see for using templating is just having to install it and call the command to marry data and template.

**Comment by BrunoGrandePhD** [comment]
I don't have bandwidth to tackle this yet, but as soon as I start working on workflows again, I'll definitely want to implement this beforehand, so it'll eventually get done. In the meantime, we can discuss how to specifically implement this, _e.g._ in our upcoming workflow meetings.

**Comment by zaro0508** [comment]
While mustache and handlebar are adequate I would recommend the jinja2 template engine for two reasons.  One, while the other two are written in javascript jinja is written in python.  This might be a consideration because we have a lot of expertise with python at Sage.  Also it might make it easier to integrate with other python tooling and for us to upstream fixes to the template engine itself.  Two, rather than using a logic-less template engine we might want support for *some* logic.  A little logic seems appropriate for scientists, which i assume will be the producers and consumers of these templates?  Logic also helps if you can't or don't want to make changes to the CWL parser functionality.  For example, IT uses jinja to create cloudformation templates because we don't have access to the cloudformation code that processes the templates.  Also I believe @tthyer has reviewed and even written some jinja templates for us so she know some of it already.   Anyways just something to consider.

**Comment by BrunoGrandePhD** [comment]
I think moving to `jinja2` as the templating engine would make sense if we had at least one use case for embedding logic into our templates. However, I can't think of any. Here, we really just want to drop in the version of the Git tag into the template in a few places. 

@denis-yuen: I hope it's okay to mention you on this thread for a quick question. Feel free to unwatch after you respond. Do you recall which organization was using templating in their CWL/WDL tools? I would like to see their repos in case we can get any inspiration for how to implement the approach with our repos. Thanks in advance!

**Comment by tthyer** [comment]
I agree with @zaro0508 that it's a bit more preferable to stick with python. But my experience with jinja2 was negligible. And @BrunoGrandePhD, I agree with you that we really don't have any use cases for doing anything complicated with templates, nor do I suspect we will in future, so that's a weak reason to consider jinja2. However, it is also incorrect that mustache, for instance is javascript-only -- it's been implemented in many other languages. Check out, for instance, [chevron](https://github.com/noahmorrison/chevron).

**Comment by denis-yuen** [comment]
No worries, I'll stay subscribed since I'm curious how this discussion plays out. 

The example that I've encountered was created by @mvdbeek for Galaxy's Intergalactic Workflow Commission actually. 
I think it is https://github.com/mvdbeek/workflow-testing-repo/blob/no_forward_slash/.github/workflows/workflow_test.yml testing+linting workflows before and uploading to https://github.com/iwc-workflows/sars-cov-2-variant-calling which is https://dockstore.org/workflows/github.com/iwc-workflows/sars-cov-2-variant-calling/COVID-19%20variation%20analysis%20on%20Illumina%20metagenomic%20data:master?tab=info on Dockstore

**Comment by denis-yuen** [comment]
Reading backwards, you can probably try out a new feature, filters, which would allow you to do the same thing within one repo and indicating which branches to send to Dockstore 

https://docs.dockstore.org/en/develop/getting-started/github-apps/github-apps.html?highlight=filters

**Comment by BrunoGrandePhD** [comment]
Thanks, @denis-yuen! We won't be able to fully benefit from the Dockstore GitHub app until command-line tools are supported (in addition to workflows). It's good to know though about filters when we do switch!
